android.enableJetifier=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
org.gradle.jvmargs=-Xmx1536m -XX:+UseG1GC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.vfs.watch=true
# AAPT2 override handled via build-tools wrapper
